version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: local.Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app
    ports:
      - "8000:8000"
    env_file:
      - envs/.env.dev
    restart: always
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - envs/.env.dev.db
    ports:
      - "5432:5432"

volumes:
  postgres_data: