# Generated by Django 3.1.5 on 2021-10-28 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211027_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='explanation',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
