# Generated by Django 3.1.5 on 2021-10-28 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('M', 'M'), ('F', 'F')], max_length=20),
        ),
    ]
